eureka:
 client:
 serviceUrl:
 defaultZone: http://eureka-primary:8761/eureka,http://eureka-secondary:8762/eureka
---
spring:
 profiles: lazy
activities: jestem z activity lazy,alto eat a cookie,alto take a nap
---
spring:
 profiles: crazy
activities: jestem z activity crazy, acto run a marathon, acto go hiking
