eureka:
 client:
 serviceUrl:
 defaultZone: http://eureka-primary:8761/eureka,http://eureka-secondary:8762/eureka
---
spring:
 profiles: lazy
activities: to grab a bear,to eat a cookie,to take a nap
---
spring:
 profiles: crazy
activities: to run a marathon, to go hiking
