---
spring:
  profiles: eureka-primary
server:
  port: 8761
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-Url:
      defoultZone: http://eureka-secondary:8762/eureka
  instance:
    hostname: eureka-primary
---
spring:
  profiles: eureka-secondary
server:
  port: 8762
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-Url:
      defoultZone: http://eureka-primary:8761/eureka
  instance:
    hostname: eureka-secondary
