spring:
  cloud:
    config:
      server:
        git:
          uri: file:///Users/Student/Desktop/szkolenie/mojeProjekty
  application:
    name: config-server
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://eureka-primary:8762/eureka