---
spring:
  profiles: polite
  application:
    name: decision-service
  cloud:
    config:
      uri: http://localhost:8888
server:
  port: 8000
---
spring:
  profiles: rough
  application:
    name: decision-service
  cloud:
    config:
      uri: http://localhost:8888
server:
  port: 8001